---

exclude_paths:
- 'cime/**'
- 'components/cam/**'
- 'components/cice/**'
- 'components/clm/**'
- 'components/homme/**'
- 'components/mosart/**'
- 'components/mpas-albany-landice/**'
- 'components/mpas-ocean/**'
- 'components/mpas-seaice/**'
- 'components/mpas-source/**'
- 'codemeta.json'
- 'CONTRIBUTING.md'
- 'LICENSE'
- 'README.md'
- 'run_e3sm.template.csh'
- 'components/scream/extern/**'
