language: cpp
sudo: false
dist: trusty

os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - lcov

after_success:
# Source: https://github.com/codecov/example-cpp11-cmake
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info
- lcov --remove coverage.info 'extern/catch2/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

git:
  submodules: false

branches:
  only:
  - master

script:
- cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=g++-6 -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" components/scream
- make -j 2
- make test
