language: cpp
sudo: false
dist: trusty

os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gfortran
    - lcov
    - libopenmpi-dev
    - openmpi-bin
    - python3

git:
  submodules: false

branches:
  only:
  - master

script:
- git clean -fd
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export OMPI_CXX=$(which g++-6); fi
- gfortran --version
- git config submodule.externals/kokkos.url https://github.com/E3SM-Project/kokkos.git
- git submodule update --init externals/kokkos
- cd components/scream
- CTEST_PARALLEL_LEVEL=4 ./scripts/test-all-scream mpicxx -m generic-desktop-debug -c '-DSCREAM_TEST_MAX_THREADS=4 -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"'

after_success:
# Source: https://github.com/codecov/example-cpp11-cmake
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info
- lcov --remove coverage.info 'extern/*' --output-file coverage.info
- lcov --remove coverage.info 'kokkos/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
