version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: bash .circleci/setup.sh
      - run: bash .circleci/checkout.sh
      - run: wget https://dabdceba-6d04-11e5-ba46-22000b92c6ec.e.globus.org/containers/public/e3sm.sif
      - run:
          command: singularity exec --hostname singularity e3sm.sif .travis/run.sh
          no_output_timeout: 60m
